apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1759788822
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-10-06T22:13:54Z"
  generation: 1
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: prometheus-1759788822
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: 0.28.1
    helm.sh/chart: prometheus-2.1.23
  name: prometheus-1759788822-alertmanager
  namespace: default
  resourceVersion: "515516"
  uid: ffd8246c-1e20-4dea-9528-66522e8c3062
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: prometheus-1759788822
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus
  serviceName: prometheus-1759788822-alertmanager-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: alertmanager
        app.kubernetes.io/instance: prometheus-1759788822
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/part-of: prometheus
        app.kubernetes.io/version: 0.28.1
        helm.sh/chart: prometheus-2.1.23
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: alertmanager
                  app.kubernetes.io/instance: prometheus-1759788822
                  app.kubernetes.io/name: prometheus
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - args:
        - --config.file=/opt/bitnami/alertmanager/conf/alertmanager.yaml
        - --storage.path=/opt/bitnami/alertmanager/data
        - --web.listen-address=0.0.0.0:9093
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/bitnamilegacy/alertmanager:0.28.1-debian-12-r15
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: http
          protocol: TCP
        - containerPort: 9094
          name: tcp-cluster
          protocol: TCP
        - containerPort: 9094
          name: udp-cluster
          protocol: UDP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /-/ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: 2Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /opt/bitnami/alertmanager/conf
          name: config
          readOnly: true
        - mountPath: /bitnami/alertmanager/data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      serviceAccount: prometheus-1759788822-alertmanager
      serviceAccountName: prometheus-1759788822-alertmanager
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: empty-dir
      - configMap:
          defaultMode: 420
          name: prometheus-1759788822-alertmanager
        name: config
      - emptyDir: {}
        name: data
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: prometheus-1759788822-alertmanager-8f54c459
  observedGeneration: 1
  replicas: 1
  updateRevision: prometheus-1759788822-alertmanager-8f54c459
  updatedReplicas: 1
