apiVersion: v1
kind: Service
metadata:
  name: argo-cd-1758916987-redis-master
  namespace: default
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: argo-cd-1758916987
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 8.2.1
    helm.sh/chart: redis-22.0.5
  annotations:
    meta.helm.sh/release-name: argo-cd-1758916987
    meta.helm.sh/release-namespace: default
  selfLink: /api/v1/namespaces/default/services/argo-cd-1758916987-redis-master
status:
  loadBalancer: {}
spec:
  ports:
    - name: tcp-redis
      protocol: TCP
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: argo-cd-1758916987
    app.kubernetes.io/name: redis
  clusterIP: 10.101.181.214
  clusterIPs:
    - 10.101.181.214
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
