apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-582
  namespace: default
  labels:
    app.kubernetes.io/instance: nginx-582
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.29.1
  annotations:
    meta.helm.sh/release-name: nginx-582
    meta.helm.sh/release-namespace: default
  selfLink: /api/v1/namespaces/default/serviceaccounts/nginx-582
spec: {}
automountServiceAccountToken: false
